AllCops:
  Exclude:
    - db/**/*
    - frontend/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/**/*
